### ISSUE TITLE
Crash on starting editor

### ISSUE THREAD

**Issue by rcorre** [fyrox-book/fyrox-book.github.io#50]
After running the following:

```
cargo install fyrox-template
fyrox-template init --name fyrox_test --style 2d
cd fyrox_test/
RUST_BACKTRACE=1 cargo run --package editor 
```

The editor stays open as long as it isn't focused, but if I focus it and move the mouse around, it crashes:

```
thread 'main' panicked at /home/rcorre/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fyroxed_base-0.19.0/src/lib.rs:2612:14:
called `Result::unwrap()` on an `Err` value: ExitFailure(1)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1077:23
   4: fyroxed_base::Editor::run
             at /home/rcorre/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fyroxed_base-0.19.0/src/lib.rs:2467:9
   5: editor::main
             at ./editor/src/main.rs:16:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Some system info, let me know if you need more:
```
[rcorre@junon ~]$ uname -sr
Linux 6.6.8-arch1-1
[rcorre@junon ~]$ glxinfo | grep OpenGL
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 530 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.3.2-arch1.2
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.3.2-arch1.2
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.3.2-arch1.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

```
[rcorre@junon fyrox_test]$ cat Cargo.toml 

[workspace]
members = ["editor", "executor", "executor-wasm", "executor-android", "game"]
resolver = "2"

[workspace.dependencies.fyrox]
version = "0.32.0"
[workspace.dependencies.fyroxed_base]
version = "0.19.0"

# Optimize the engine in debug builds, but leave project's code non-optimized.
# By using this technique, you can still debug you code, but engine will be fully
# optimized and debug builds won't be terribly slow. With this option, you can
# compile your game in debug mode, which is much faster (at least x3), than release.
[profile.dev.package."*"]
opt-level = 3
```

**Comment by mrDIMAS** [comment]
X11 or Wayland?

**Comment by mrDIMAS** [comment]
If it is Wayland, just `fyrox-template upgrade --version=nightly` in your game's root directory. Long story short - Wayland server seem to disconnect randomly on latest `winit` crate and I did a workaround on the latest version of the engine that is on GitHub.

**Comment by rcorre** [comment]
Yes, it is wayland. Nightly hasn't crashed so far, thanks for the quick response!
